---
- name: Create .pyenvrc file
  template:
    src: pyenvrc.j2
    dest: "{{ ansible_env.HOME }}/.pyenvrc"
    mode: 0644

- name: Create .condarc file
  template:
    src: condarc.j2
    dest: "{{ ansible_env.HOME }}/.condarc"
    mode: 0644
  when: python_versions | select('search', 'conda') | list

- name: Set global Python version
  block:
    - name: Check global python
      shell: ". {{ ansible_env.HOME }}/.pyenvrc && pyenv global"
      args:
        executable: /bin/bash
      register: global_python_version
      changed_when: False

    - name: Set global python version
      shell: ". {{ ansible_env.HOME }}/.pyenvrc && pyenv global system"
      args:
        executable: /bin/bash
      when: global_python_version.stdout | lower != "system"
  when: global_python | lower == 'system'

- name: Install Python interpreters
  shell: ". {{ ansible_env.HOME }}/.pyenvrc && pyenv install {{ item }}"
  args:
    executable: /bin/bash
    creates: "{{ pyenv_root }}/versions/{{ item }}/bin/python"
  with_items: "{{ python_versions }}"
