---
- name: Debug pyenv version
  debug:
    msg: "Version of pyenv to install: {{ pyenv.version }}"

- name: Install pyenv
  git:
    repo: "{{ pyenv.repo }}"
    dest: "{{ pyenv.path }}"
    version: "{{ pyenv.version }}"

- name: Create .pyenvrc file
  template:
    src: pyenvrc.j2
    dest: "{{ ansible_env.HOME }}/.pyenvrc"
    mode: 0644

- name: Create .condarc file
  template:
    src: condarc.j2
    dest: "{{ ansible_env.HOME }}/.condarc"
    mode: 0644
  when: python_versions | select('search', 'conda') | list
