---
- name: Install system python
  become: yes
  package:
    name: "{{ item }}"
    state: present
  register: result
  retries: 3
  until: result is succeeded
  with_items: "{{ system_python_packages }}"

- name: Link Python2 to python3
  block:
    - name: Check python link
      stat:
        path: /usr/bin/python
      register: python_path_stat

    - name: Link python to python3
      become: yes
      file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link
        owner: root
        group: root
        mode: 0755
      when: python_path_stat.stat.exists and not python_path_stat.stat.islnk
  when: link_python | bool

- name: Form merged list of pip packages
  set_fact:
    merged_pip_packages: "{{ default_pip_packages | union(pip_packages) }}"

- name: Show merged pip packages
  debug:
    var: merged_pip_packages

- name: Install pip packages into system python
  pip:
    name: "{{ merged_pip_packages }}"
    extra_args: --user
    executable: pip3
  when: merged_pip_packages | length > 0
