---
- name: Debug pyenv version
  debug:
    msg: "Version of pyenv to install: {{ pyenv_reference }}"

- name: Install pyenv
  git:
    repo: "{{ pyenv_repo }}"
    dest: "{{ pyenv_root }}"
    version: "{{ pyenv_reference }}"

- name: Debug pyenv-virtualenv version
  debug:
    msg: "Version of pyenv-virtualenv to install: {{ pyenvvirtualenv_reference }}"

- name: Install pyenv-virtualenv
  git:
    repo: "{{ pyenvvirtualenv_repo }}"
    dest: "{{ pyenv_root }}/plugins/pyenv-virtualenv"
    version: "{{ pyenvvirtualenv_reference }}"
