---
- name: Check for python {{ item }}
  stat:
    path: "{{ pyenv.path }}/versions/{{ item }}"
  register: python_exists

- name: Install python {{ item }}
  raw: "PYENV_ROOT={{ pyenv.path }} {{ pyenv.path }}/bin/pyenv install {{ item }}"
  notify: rehash
  when: python_exists.stat is defined and not python_exists.stat.exists
